import * as React from 'react';
import Box from '@mui/material/Box';
import Stepper from '@mui/material/Stepper';
import Step from '@mui/material/Step';
import StepLabel from '@mui/material/StepLabel';
import StepContent from '@mui/material/StepContent';
import Typography from '@mui/material/Typography';

const steps = [
    {
        label: 'Fact Extraction',
        description: `The fact extraction phase gathers facts about the system being investigated`,
    },    
    {
        label: 'Architectural Recovery',
        description: `Based on the facts extracted about about a system, the architectural recovery
                    phase creates a model of the architecture`,
  },
  {
        label: 'Smell Detection',
        description: `The smell detection phase detects issues, or "smells", in the model generated by
                    the architectural recovery phase`,
  },
  {
        label: 'Metrics',
        description: `The metrics phase measures a variety of aspects of the architecture`,
  },
];

export default function Descriptions() {
  const [activeStep, setActiveStep] = React.useState(0);

  const handleNext = () => {
    setActiveStep((prevActiveStep) => prevActiveStep + 1);
  };

  const handleBack = () => {
    setActiveStep((prevActiveStep) => prevActiveStep - 1);
  };

  const handleReset = () => {
    setActiveStep(0);
  };

  return (
    <Box sx={{ flexGrow: 1, mx: "auto", width: '30%', textAlign: "left"}}>
      <Stepper activeStep={activeStep} orientation="vertical">
        {steps.map((step, index) => (
          <Step key={step.label} active = {true}>
            <StepLabel>
              {step.label}
            </StepLabel>
            <StepContent>
              <Typography>{step.description}</Typography>
            </StepContent>
          </Step>
        ))}
      </Stepper>
    </Box>
  );
}